op = int(input("Digite o num mes "))
match op: 
    case 1: print("jan")
    case 2: print("fev")
    case 3: print("mar")
    case 4: print("abril")
    case 5: print("maio")
    case 6: print("junho")
    case 7: print("julho")
    case 8: print("agosto")
    case 9: print("setembro")
    case 10: print("outubro")
    case 11: print("Novembro ")
    case 12: print("Dezembro")
    case _: print("invalido")